<?php
namespace App\Controllers\Repositories;

use App\Connection;
use App\Controllers\Traits\FasternetClienteTrait; //Pesquisa o cliente
use App\Controllers\Traits\FasternetTarefasTrait; //Necessário para buscar ccc cookie
use App\Controllers\Traits\FasternetAutenticacaoTrait; //Loga na Fasternet
use App\Controllers\Traits\FasternetConfereClienteTrait; //Busca dados LGPD
use App\Controllers\Traits\FasternetCookieUsuarioTrait; //Adiciona os cookies de usuário
use App\Controllers\Traits\FasternetNovaTarefaUrlTrait;//Cria uma url para abertura de protocolo
use App\Controllers\Traits\FasternetCriaTarefaTrait; //cria o protocolo no ADM, não fazer funcionar. Precisa de parâmetros de html select
use App\Controllers\Traits\FasternetDhcpComCookieTrait; //Busca os dados da conexão
use App\Controllers\Traits\FasternetTesteTarefaTrait; //busca ultimos protocolos

class FasternetRepository extends Connection
{
    private $cookieFile;
    private $cccCookie;
    public $userAdm;
    public $passAdm;
    public $nameAdm;
    public $userId;


    public function __construct()
    {
        $this->userAdm = $_SESSION['admUser'] ?? 'nouser';
        $this->passAdm = $_SESSION['admPass'] ?? 'nopass';
        $this->nameAdm = $_SESSION['admName'] ?? 'noname';
        $this->userId = $_SESSION['user_id'] ?? 'noid';

        parent::__construct();
        $this->cookieFile = __DIR__ . "/../" . $this->userId ."_cookies.txt";


        $this->autenticarViaConnectDB(); 
        $this->capturarCookiesUsuario(); //Adicoiona ccc e cookies de usuário no arquivo
        
    }

    use FasternetClienteTrait, 
    FasternetTarefasTrait, 
    FasternetAutenticacaoTrait, 
    FasternetConfereClienteTrait, 
    FasternetCookieUsuarioTrait,
    FasternetNovaTarefaUrlTrait,
    FasternetCriaTarefaTrait,
    FasternetDhcpComCookieTrait,
    FasternetTesteTarefaTrait;


    private function atualizarOuAdicionarCookie($host, $nome, $valor)
    {
        $linhaNova = "$host\tFALSE\t/\tFALSE\t0\t$nome\t$valor";

        if (!file_exists($this->cookieFile)) {
            $cabecalho = "# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n";
            file_put_contents($this->cookieFile, $cabecalho . $linhaNova . "\n");
            return;
        }

        $linhas = file($this->cookieFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $cabecalho = [];
        $cookies = [];
        $atualizado = false;

        foreach ($linhas as $linha) {
            if (strpos($linha, "#") === 0 || trim($linha) === "") {
                $cabecalho[] = $linha;
            } elseif (preg_match("/^\Q$host\E\tFALSE\t\/\tFALSE\t0\t$nome\t/", $linha)) {
                $cookies[] = $linhaNova;
                $atualizado = true;
            } else {
                $cookies[] = $linha;
            }
        }

        if (!$atualizado) {
            $cookies[] = $linhaNova;
        }

        $conteudoFinal = implode("\n", array_merge($cabecalho, [""], $cookies)) . "\n";
        file_put_contents($this->cookieFile, $conteudoFinal);
    }
  
    public function extrairCodigoG()
    {
        $html = $this->requisitarTarefasIndexPg();

        // Escapa o valor de $this->userADM para uso seguro na expressão regular
        $usuarioLogin = preg_quote($this->userAdm, '/');

        // Expressão regular para capturar o valor de g=...
        preg_match("/blank\.asp\?usuariologin={$usuarioLogin}&g=(\d+)/", $html, $matches);

        if (isset($matches[1])) {
            $codigoG = $matches[1];
            $urlFinal = "http://www2.fasternet.com.br/fasteradm/blank.asp?usuariologin={$this->userAdm}&g={$codigoG}";

            // Salva o cookie 'ccc' com o valor extraído
            $this->atualizarOuAdicionarCookie('www2.fasternet.com.br', 'ccc', $codigoG);

            return $codigoG;
        } else {
            echo "<pre>Não foi possível extrair o código 'g'.</pre>";
            return null;
        }
    }

    private function extrairCookie($nome)
    {
        if (!file_exists($this->cookieFile)) return null;

        $linhas = file($this->cookieFile);
        foreach ($linhas as $linha) {
            if (strpos($linha, "\t") !== false) {
                $partes = explode("\t", $linha);
                if (isset($partes[5]) && trim($partes[5]) === $nome && isset($partes[6])) {
                    return trim($partes[6]);
                }
            }
        }

        return null;
    }

}
